version: '3.8'

services:
  api-service:
    build: .
    ports:
      - "11434:11434"
    environment:
      - NODE_ENV=production
      - PORT=11434
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - ALLOWED_ORIGINS=https://soundbysoundslowly.com,https://www.soundbysoundslowly.com
      - LOG_LEVEL=info
      - REQUIRE_API_KEY=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:11434/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
